### ISSUE TITLE
Production GNIS Setup

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/k8s-cluster#10]
GNIS-LD is, as a product, is ready to be released to the production Kubernetes cluster. On the production cluster we'll need a few things first.

- [x] `gnis` namespace
- [x] `gnis` user
- [x] A [CephFS persistent volume](https://github.com/DataONEorg/gnis-deployment/issues/9)
- [x] [Updated Ingress rules](https://github.com/DataONEorg/gnis-deployment/issues/8)

**Comment by ThomasThelen** [comment]
The cert-manager requirement has been fulfilled so I checked it off of your list; logs and proof [here](https://github.com/DataONEorg/gnis-deployment/issues?q=is%3Aissue+is%3Aclosed)

**Comment by ThomasThelen** [comment]
Updating this issue to track that https://gnis-ld.org:30443/ has now been deployed. Our last issue to resolve is the port 80/443 configuration.

**Comment by gothub** [comment]
@ThomasThelen all tasks in this issue have been completed - pls reopen this if there are other items that need to be done.
