### ISSUE TITLE
set RBAC using serviceaccount script

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/k8s-cluster#29]
The current serviceaccount script doesn't apply default RBAC rules. Reconfigure to apply the template file.

**Comment by mbjones** [comment]
I set up the application-context.yaml file with the SERVICE_ACCOUNT env variable, and use `envsubst` to substitute in the servie account name and then apply that. See the new `apply_rbac` function in the account creation script.

@gothub I tested and this seems to create RBAC properly in the initial service account creation. Please review and see if it looks good to you.

**Comment by gothub** [comment]
Yes, looks good. I tested in dev k8s and it worked for me.
